### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by mb720** [janestreet/re2#10]
Hi and thanks a lot for these bindings!

I was wondering where I can find any documentation about Re2 with regard to its objects and functions.
I've seen information about the [syntax](https://re2.googlecode.com/hg/doc/syntax.html) of the regular expressions it accepts but nothing about its interface.

Thanks in advance!

Matthias

**Comment by agarwal** [comment]
If you mean the OCaml API, then see [Re2_internal_intf](https://github.com/janestreet/re2/blob/master/src/re2_internal_intf.ml).

**Comment by bmillwood** [comment]
Well, and parser.mli and possibly the other interfaces.

The next public release should include some actual generated HTML docs again, since we're switching away from camlp4.
