### ISSUE TITLE
How to pin re2 with opam

### ISSUE THREAD

**Issue by sepeth** [janestreet/re2#13]
I think I found a bug in this, but in order to fix it, I need to play with the source code first. For this reason, I tried to pin re2 with opam, but I got this:

```
$ opam pin add re2 .
...
The following dependencies couldn't be met:
  - re2 -> ppx_hash
Your request can't be satisfied:
  - No package named ppx_hash found.
...
```

Indeed, ppx_hash is not in opam repository yet. So I thought, I can pin it as well, and get away with this. But it didn't work because it required base, and so on. So I stopped. I tried to install re2 and ppx_hash manually, without using opam, with make, but couldn't go far either (Btw, I am on OS X, which I believe jenga doesn't support, which I couldn't much information about it anyway). I am new in OCaml world, I tried many things already, could you give me a direction to install re2 from my sources?

**Comment by diml** [comment]
Sure, you have two choices:
- you can build re2 from sources using the 113.33 branch which correspond to what is in opam at the moment
- you can use our development opam repository which contains the packages for the development versions of all the Jane Street packages:

```
$ opam repo add https://github.com/janestreet/opam-repository.git
```

**Comment by sepeth** [comment]
Thanks @diml, the first choice worked ^_^
