### ISSUE TITLE
114.20+69 doesn't build on OS X 

### ISSUE THREAD

**Issue by tiash** [janestreet/re2#16]
- There seems to be an issue with building the .so missing (all?) symbols for x86_64.
   Changing the make scripts to use the native c++ (clang) instead of $CXX (apparently g++) seems to fix this.

- The generation of [options.ml] from [options.mlp] doesn't work with the Xcode 8.2 version of CPP (it leaves ' ## ' tokens and inserts space after the '`'.

- Even after fixing these [opam] still refuses to install the package (though jbuilder exits 0).
   There are a bunch of warnings:
```
# re2/onepass.cc:176:18: warning: unused typedef 'kEmptyShift_disagrees_with_kEmptyAllFlags' [-Wunused-local-typedef]
# [...]
#                  ^
# re2/onepass.cc:179:18: warning: unused typedef 'kMaxCap_disagrees_with_kMaxOnePassCapture' [-Wunused-local-typedef]
#                  kMaxCap_disagrees_with_kMaxOnePassCapture);
#                  ^
# 2 warnings generated.
# re2/prog.cc:317:45: warning: unused typedef 'wordsize' [-Wunused-local-typedef]
#   COMPILE_ASSERT(8*sizeof(v.Word(0)) == 32, wordsize);  
```

**Comment by diml** [comment]
Ok, I think this is now fixed
