### ISSUE TITLE
How to build with clang?

### ISSUE THREAD

**Issue by vbgl** [janestreet/re2#21]
I try to build re2 version v0.9.0 on macOS using the clang compiler (version 4.0.0) and `jbuilder` version 1.0-beta7. I get the following error:

```
bash: g++: command not found
make[1]: *** [Makefile:161: obj/util/arena.o] Error 127
```

If I remove the line that chooses `g++` instead of `cxx` (https://github.com/janestreet/re2/blob/master/src/re2_c/jbuild#L25), the following error arises:

```
          cc src/stubs.o (exit 1)
[…]
stubs.cpp:1:10: fatal error: 'vector' file not found
#include <vector>
         ^~~~~~~~
1 error generated.
```

It appears that the source file `stubs.cpp` is compiled with `cc` instead of `cxx`. Any idea on how to fix this?

**Comment by dwang20151005** [comment]
@diml I have no dev experience on MacOS and don't even have access to any MacOS test machines.  Would it be possible for you to investigate this?

**Comment by diml** [comment]
@dwang20151005 sure.

@vbgl `stubs.cpp` is compiled by jbuilder directly. `cc` comes from from the output of `ocamlc -config`. Basically jbuilder uses same C compiler OCaml uses to build C files. The expectation is that the C compiler will choose the language based on the extension. It works fine with gcc, any idea why it doesn't work here?

**Comment by vbgl** [comment]
Is the C compiler used to build OCaml really required to correctly compile C++ programs?

Is this a jbuilder/dune bug?

**Comment by diml** [comment]
I did it this way initially as I don't know the conventions for building C++. @vbgl feel free to open a ticket on dune, it might be possible to do something, such as allowing user to specify an alternative C++ compiler.

**Comment by MattWindsor91** [comment]
This is still a pain point on v0.12.0: specifically, whenever using an opam switch on macOS that uses the system compiler, and the system compiler is the Homebrew version, we have that `ocamlc -config` reports `native_c_compiler: clang -O2 -fno-strict-aliasing -fwrapv -D_FILE_OFFSET_BITS=64 -D_REENTRANT`; `clang` on my system is the Homebrew (non-Apple) version, and this particular compiler emits a lot of extremely confused errors that appear to be related to ocaml's `version` file shadowing part of that compiler's stdlib (!):

```
In file included from stubs.cpp:1:
In file included from /usr/local/opt/llvm/bin/../include/c++/v1/vector:275:
In file included from /usr/local/opt/llvm/bin/../include/c++/v1/__bit_reference:15:
In file included from /usr/local/opt/llvm/bin/../include/c++/v1/bit:24:
/usr/local/lib/ocaml/version:1:1: error: expected unqualified-id
4.08.1
^
/usr/local/lib/ocaml/version:3:3: error: invalid preprocessing directive
# The version string is the first line of this file.
  ^
/usr/local/lib/ocaml/version:4:3: error: invalid preprocessing directive
# It must be in the format described in stdlib/sys.mli
  ^
```

If I switch over to a switch with a locally built compiler, `ocamlc -config` instead shows the compiler as `cc`, which links to the macOS-provided Apple version of `clang`, and this compiler works for some reason.

I figure this is still more a dune problem than a re2 problem (Ie I could solve it if I could tell `dune` to use `cc`, not `clang`), so, if GitHub doesn't automatically ping [the corresponding dune issue](https://github.com/ocaml/dune/issues/949), I'll drop a comment there too.

**Comment by jeremiedimino** [comment]
This seems very similar to #28 and there is a fix in the pipe. So I'm closing this.
