### ISSUE TITLE
The library has too many dependencies

### ISSUE THREAD

**Issue by cakeplus** [janestreet/re2#6]
Does it really need to have so many dependencies?
```
cakeplus@counterfeit-monkey:~$ opam install re2
The following actions will be performed:
 - install pipebang.110.01.00 [required by re2]
 - install fieldslib.109.20.03 [required by re2]
 - install comparelib.109.60.00 [required by re2]
 - install bin_prot.111.03.00 [required by re2]
 - install type_conv.111.13.00 [required by re2]
 - install sexplib.111.17.00 [required by re2]
 - install variantslib.109.15.03 [required by re2]
 - install enumerate.111.08.00 [required by re2]
 - install ounit.2.0.0 [required by re2]
 - install herelib.109.35.02 [required by re2]
 - install pa_test.111.08.00 [required by re2]
 - install typerep.111.17.00 [required by re2]
 - install pa_ounit.109.53.02 [required by re2]
 - install pa_bench.109.55.02 [required by re2]
 - install custom_printf.111.03.00 [required by re2]
 - install core_kernel.111.17.00 [required by re2]
 - install core.111.17.00 [required by re2]
 - install re2.111.08.00
18 to install | 0 to reinstall | 0 to upgrade | 0 to downgrade | 0 to remove
Do you want to continue ? [Y/n] y
```

I mean, it's not much of a problem in the modern age of OPAM and cheap hardware, but still... Come on, it's a friggin regexp engine! `ocaml-pcre`, in comparison, has no dependencies at all.

If the dependencies are needed to implement a Core-compatible interface, then perhaps this Core-specific interface could be made optional; and an additional, Core-free, interface could be bundled with the library? It could reuse the very same C stubs.

If I decide to use `re2` for an upcoming project, then I might contribute the simplified API myself, not wishing to depend on all that enterprise stuff :-)

**Comment by fxfactorial** [comment]
@diml core_kernel would be better. It seems that all its really using from core is Result and friends.

**Comment by bmillwood** [comment]
I made this change internally and it should come out in the next release.
