### ISSUE TITLE
Incorrect OCamldoc for replace and replace_exn

### ISSUE THREAD

**Issue by rgrinberg** [janestreet/re2#9]
https://github.com/janestreet/re2/blob/master/src/re2_internal_intf.ml#L200-L202

Reproduced here in case the link goes stale:

```
    @param f if [f] returns [None], the original match is put back in; if it
    returns [Some s] then [s] is substituted for the matched string.  (So,
    returning Some "" means delete the matched string.)
```

```ocaml
val replace
  :  ?sub:id_t
  -> ?only:int
  -> f:(Match.t -> string)
  -> t
  -> string
  -> string Or_error.t
```

`~f` in fact doesn't return an option.

**Comment by bmillwood** [comment]
The comment will be deleted in the next version (once the option stuff is gone, the function is too simple to say much useful about)

**Comment by bmillwood** [comment]
Maybe the version after next. In any case, good catch, thanks.
